apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: k8s-job-cleaner-job-manager
subjects:
  - kind: ServiceAccount
    name: k8s-job-cleaner
roleRef:
  kind: ClusterRole
  name: job-manager
  apiGroup: rbac.authorization.k8s.io