on:
  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - '**/README.md'
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
  workflow_dispatch:

env:
  ACTION_URL: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Get credentials
        uses: leanix/secrets-action@master
        with:
          secret-store-credentials: ${{ secrets.INJECTED_SECRET_STORE_CREDENTIALS }}

      - uses: actions/setup-go@v2
        with:
          go-version: '1.15'

      - name: Build
        run: make

      - name: Build and push image
        if: github.ref=='refs/heads/master'
        id: build-image
        uses: leanix/release-docker-image-action@master

      - name: Validate k8s config
        if: github.ref!='refs/heads/master'
        uses: leanix/k8s-deploy-action@master
        with:
          dry_run: true
          environment: prod
          namespace: k8s-job-cleaner
          tag: ${{ steps.build-image.outputs.tag }}

      - name: Deploy master to production clusters
        if: github.ref=='refs/heads/master'
        uses: leanix/k8s-deploy-action@master
        with:
          namespace: k8s-job-cleaner
          environment: prod
          tag: ${{ steps.build-image.outputs.tag }}

      - name: Send build / release success message
        if: startsWith(github.ref, 'refs/tags/') || github.ref=='refs/heads/master'
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ env.SLACK_TOKEN }}
          slack-channel: '#team-atlas-notifications'
          slack-text: |
            :thumbsup: ${{ github.repository }} successfully built / released for version ${{ github.ref }}
            ${{ env.ACTION_URL }}

      - name: Send build / release fail message
        if: failure() && (startsWith(github.ref, 'refs/tags/') || github.ref=='refs/heads/master')
        uses: archive/github-actions-slack@v1.0.0
        with:
          slack-bot-user-oauth-access-token: ${{ env.SLACK_TOKEN }}
          slack-channel: '#team-atlas-notifications'
          slack-text: |
            :thumbsdown: ${{ github.repository }} could not be built / released for version ${{ github.ref }}
            ${{ env.ACTION_URL }}